### ISSUE TITLE
be more explicit that you must use Scala 2.11 not 2.12?

### ISSUE THREAD

**Issue by SethTisue** [scala-android/scala-android.github.io#20]
I think this would be very easy for a newbie to miss

evidence: https://www.reddit.com/r/scala/comments/5b3x41/question_scala_212_on_android/?st=iv45m859&sh=5ae78f6a

**Comment by SethTisue** [comment]
P.S. the website looks great. super glad y'all stepped up and did this.

**Comment by soc** [comment]
That's a good idea, thanks!

**Comment by SethTisue** [comment]
closing since the repo seems abandoned
