### ISSUE TITLE
The TypedActivity example needs updating

### ISSUE THREAD

**Issue by abderrahim** [scala-android/scala-android.github.io#22]
http://scala-android.org/tips_and_tricks-typed_resources/ refers to TypedActivity, which no longer exists (since http://scala-android.org/releases/1_4_0/).

**Comment by abderrahim** [comment]
The example can work by replacing TypedActivity with TypedFindView. There is also TypedViewHolder.

**Comment by soc** [comment]
Thanks for the report! Would you be able to do a pull request to fix it?
